name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main  # lub inna gałąź, na której pracujesz
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd docs
          # Tutaj dodaj komendy budujące Twoją stronę, jeśli są potrzebne
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # Ścieżka do Twoich plików
